<?php
/*
ez/pats/templates/contrato_pats_base.php

Contrato PATS completo en HTML para vista previa, firma digital y guardado.

IMPORTANTE PARA DESARROLLADOR:
- Este template contiene el contrato completo, no solo carátula/resumen.
- La firma debe guardar este HTML completo + hash + firma + IP + user agent.
- Si después se imprime o genera PDF, debe salir de este HTML guardado.
- Si es menor: el paciente/afiliado real es el menor; el firmante legal y administrador es el tutor.
- Si es extranjero/no mexicano: no se exige CURP, RFC/CIF ni INE; se usa identificación oficial o pasaporte.
- En menores, la CIF/constancia fiscal corresponde al tutor cuando aplique, no al menor.
*/
$e = fn($v) => pats_h($v ?? '');
$siMenor = !empty($data['es_menor_bool']);
$siDependiente = !empty($data['es_dependiente_bool']);
$requiereResponsable = !empty($data['requiere_responsable_bool']);
$siAdultoMayor = !empty($data['es_adulto_mayor_bool']);
$mx = (($data['afiliado_nacionalidad_tipo'] ?? 'MEXICANA') === 'MEXICANA');
$tutorMx = (($data['tutor_nacionalidad_tipo'] ?? 'MEXICANA') === 'MEXICANA');
$firmanteLabel = $requiereResponsable ? ($siMenor ? 'MAMÁ, PAPÁ O TUTOR / FIRMANTE' : 'RESPONSABLE AUTORIZADO / FIRMANTE') : 'EL AFILIADO';
$afiliadoLabel = $siMenor ? 'EL PACIENTE MENOR / AFILIADO' : ($siDependiente ? 'EL PACIENTE / AFILIADO REPRESENTADO' : 'EL AFILIADO');
$identificacionAfiliado = $mx ? 'credencial para votar vigente expedida por el Instituto Nacional Electoral' : 'identificación oficial o pasaporte vigente expedido por autoridad competente';
$anexoId = $mx ? 'Identificación oficial de “EL AFILIADO”' : 'Identificación oficial o pasaporte de “EL AFILIADO”';
$anexoFiscal = $mx ? 'Constancia de Situación Fiscal de “EL AFILIADO”, si aplica' : 'No aplicable salvo que declare RFC mexicano';
$curpAnexoTexto = $mx ? 'Clave Única de Registro de Población' : 'No aplicable por nacionalidad extranjera/no mexicana';
$firmanteNombre = $data['nombre_firmante'] ?: 'Pendiente de firma';
$nombreAfiliado = $data['afiliado_nombre_completo'] ?: 'Pendiente';
$domAfiliado = $data['afiliado_domicilio_completo'] ?: 'Pendiente';
$beneficiarioDirecto = strtoupper((string)($data['beneficiario_directo'] ?? 'SI')) === 'NO' ? 'NO' : 'SI';
?>
<style>
  .pats-contract{font-family:Arial,Helvetica,sans-serif;color:#172033;font-size:12px;line-height:1.52;background:#fff;padding:4px}
  .pats-contract h1,.pats-contract h2,.pats-contract h3,.pats-contract h4{text-align:center;margin:12px 0 8px;color:#0d1b3e}
  .pats-contract h1{font-size:16px;text-transform:uppercase;letter-spacing:.05em}
  .pats-contract h2{font-size:15px;text-transform:uppercase;letter-spacing:.04em}
  .pats-contract h3{font-size:13px;text-transform:uppercase;letter-spacing:.08em}
  .pats-contract h4{font-size:12px;text-align:left;text-transform:uppercase;margin-top:12px}
  .pats-contract p{margin:6px 0;text-align:justify}
  .pats-contract ul{margin:6px 0 8px 18px;padding:0}.pats-contract li{margin:4px 0;text-align:justify}
  .pats-contract table{width:100%;border-collapse:collapse;margin:8px 0 12px}.pats-contract th,.pats-contract td{border:1px solid #cbd5e1;padding:6px;vertical-align:top}.pats-contract th{background:#eef4ff;color:#0d1b3e;text-align:left}
  .pats-contract .center{text-align:center}.pats-contract .muted{color:#64748b}.pats-contract .small{font-size:10px}.pats-contract .badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#eef4ff;color:#1d4ed8;font-weight:700;margin:2px 4px 2px 0}
  .pats-contract .sign-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:28px}.pats-contract .sign-box{text-align:center;min-height:95px}.pats-contract .line{border-top:1px solid #0f172a;margin:48px 8px 6px}.pats-contract .signature-img{max-width:220px;max-height:82px;display:block;margin:0 auto 4px}
  .pats-contract .annex{page-break-before:auto;border-top:2px solid #0d1b3e;margin-top:18px;padding-top:12px}.pats-contract .page-break{page-break-before:always;border-top:1px dashed #cbd5e1;margin-top:18px;padding-top:12px}
</style>
<div class="pats-contract">
  <h1>Carátula del contrato de adquisición de tarjeta de descuento</h1>
  <p>CARÁTULA DEL CONTRATO DE ADQUISICIÓN DE TARJETA DE DESCUENTO (EN LO SUCESIVO “LA CARÁTULA”), QUE CELEBRAN POR UNA PARTE LA SOCIEDAD SEÑALADA EN EL APARTADO 1.- DE LA CARÁTULA, A QUIEN EN LO SUCESIVO SE LE DENOMINARÁ COMO “EL PRESTADOR”, REPRESENTADA EN ESTE ACTO POR LA PERSONA FÍSICA QUE SE INDICA EN EL APARTADO 2.- DE LA CARÁTULA; Y POR LA OTRA PARTE, LA PERSONA FÍSICA SEÑALADA EN EL APARTADO 5.- DE LA CARÁTULA, <?= $siMenor ? 'REPRESENTADA POR SU MAMÁ, PAPÁ O TUTOR, A QUIEN PARA EFECTOS DE BENEFICIO MÉDICO SE LE DENOMINARÁ COMO “EL AFILIADO” O “EL PACIENTE MENOR”' : ($siDependiente ? 'REPRESENTADA POR SU RESPONSABLE AUTORIZADO, A QUIEN PARA EFECTOS DE BENEFICIO MÉDICO SE LE DENOMINARÁ COMO “EL AFILIADO” O “EL PACIENTE REPRESENTADO”' : 'POR SU PROPIO DERECHO, A QUIEN EN LO SUCESIVO SE LE DENOMINARÁ COMO “EL AFILIADO”') ?>; Y CUANDO LOS ANTES NOMBRADOS ACTÚEN DE MANERA CONJUNTA, SE LES DENOMINARÁ COMO “LAS PARTES”; QUIENES SE SUJETAN AL TENOR DE LA CARÁTULA, DECLARACIONES Y CLÁUSULAS SIGUIENTES:</p>
  <?php if ($siMenor): ?><p><span class="badge">Menor de edad</span> El paciente/beneficiario real es el menor indicado en el Apartado 5; el contrato, avisos, aceptación y administración de usuario/contraseña son firmados y aceptados por su mamá, papá o tutor.</p><?php elseif ($siDependiente): ?><p><span class="badge">Paciente representado</span> El paciente/beneficiario real es la persona indicada en el Apartado 5; el contrato, avisos, aceptación y administración de usuario/contraseña son firmados y aceptados por la persona responsable autorizada.</p><?php endif; ?>
  <?php if (!$mx): ?><p><span class="badge">Afiliado extranjero/no mexicano</span> No se exige CURP, INE ni constancia fiscal mexicana; se acepta identificación oficial o pasaporte vigente, al menos frente.</p><?php endif; ?>

  <h2>C A R Á T U L A</h2>
  <table>
    <tr><th style="width:8%">Apartado</th><th style="width:42%">Definición</th><th>Respuesta</th></tr>
    <tr><td>1.-</td><td>Nombre de “EL PRESTADOR”</td><td><?= $e($data['prestador_razon_social']) ?></td></tr>
    <tr><td>2.-</td><td>Nombre del Representante Legal de “EL PRESTADOR”</td><td><?= $e($data['prestador_representante']) ?></td></tr>
    <tr><td>3.-</td><td>Domicilio de “EL PRESTADOR”</td><td><?= $e($data['prestador_domicilio']) ?></td></tr>
    <tr><td>4.-</td><td>Clave del Registro Federal de Contribuyentes de “EL PRESTADOR”</td><td><?= $e($data['prestador_rfc']) ?></td></tr>
    <tr><td>5.-</td><td>Nombre de “EL AFILIADO”</td><td><?= $e($nombreAfiliado) ?><?= $requiereResponsable ? '<br><span class="small">Paciente representado por: '.$e($data['tutor_nombre_completo'] ?: 'Pendiente').'</span>' : '' ?></td></tr>
    <tr><td>6.-</td><td>Domicilio de “EL AFILIADO”</td><td><?= $e($domAfiliado) ?></td></tr>
    <tr><td>7.-</td><td>Clave del Registro Federal de Contribuyentes de “EL AFILIADO”</td><td><?= $e($data['afiliado_rfc']) ?></td></tr>
    <tr><td>8.-</td><td>Costo <?= $e($data['frecuencia_texto']) ?> de “LA TARJETA DE DESCUENTO”</td><td><?= $e($data['monto_contrato']) ?></td></tr>
    <tr><td>9.-</td><td>Cuenta bancaria de “EL PRESTADOR” para pagos</td><td>Cuenta: <?= $e($data['prestador_cuenta_pago']) ?><br>CLABE: <?= $e($data['prestador_clabe_pago']) ?><br>Institución Bancaria: <?= $e($data['prestador_banco_pago']) ?></td></tr>
    <tr><td>10.-</td><td>Cuota de Reactivación de “LA TARJETA DE DESCUENTO”</td><td><?= $e($data['cuota_reactivacion_texto']) ?> por cada mes que se haya interrumpido el pago.</td></tr>
    <tr><td>11.-</td><td>Datos de la Tarjeta de Crédito de “EL AFILIADO”</td><td>Número de tarjeta: pendiente de confirmar por pasarela/token de pago.<br>Institución bancaria: pendiente de confirmar por pasarela. <br><span class="small">No se almacena número completo de tarjeta en este formulario.</span></td></tr>
    <tr><td>12.-</td><td>Anexos</td><td>ANEXO 1. <?= $e($anexoId) ?><br>ANEXO 2. Comprobante de domicilio de “EL AFILIADO”<br>ANEXO 3. <?= $e($anexoFiscal) ?><br>ANEXO 4. Cuotas de recuperación y/o precios base a cubrir a “EL PRESTADOR”<br>ANEXO 5. Aviso de privacidad<br>ANEXO 6. Declaración de dueño beneficiario<?= $requiereResponsable ? '<br>ANEXO 7. Documentación y aceptación de la persona responsable' : '' ?><?= $siAdultoMayor ? '<br>ANEXO OPERATIVO. Requisito adulto mayor: dos pasaportes vigentes validados' : '' ?></td></tr>
    <tr><td>13.-</td><td>Fecha de Firma del Contrato</td><td><?= $e($data['fecha_firma_larga']) ?></td></tr>
  </table>

  <div class="sign-grid">
    <div class="sign-box"><div class="line"></div><strong>“EL PRESTADOR”</strong><br><?= $e($data['prestador_razon_social']) ?><br>Representada por <?= $e($data['prestador_representante']) ?></div>
    <div class="sign-box"><?php if (!empty($data['firma_afiliado_base64'])): ?><img class="signature-img" src="<?= $e($data['firma_afiliado_base64']) ?>" alt="Firma digital"><?php else: ?><div class="line"></div><?php endif; ?><strong>“<?= $e($firmanteLabel) ?>”</strong><br><?= $e($firmanteNombre) ?><br><span class="small"><?= $requiereResponsable ? 'Firma como responsable de '.$e($nombreAfiliado) : 'La persona física señalada en el Apartado 5.- de la Carátula' ?></span></div>
  </div>

  <div class="page-break"></div>
  <h1>Contrato de adquisición de tarjeta de descuento</h1>
  <p>CONTRATO DE ADQUISICIÓN DE TARJETA DE DESCUENTO, QUE CELEBRAN POR UNA PARTE LA SOCIEDAD SEÑALADA EN EL APARTADO 1.- DE LA CARÁTULA, A QUIEN EN LO SUCESIVO SE LE DENOMINARÁ COMO “EL PRESTADOR”, REPRESENTADA EN ESTE ACTO POR LA PERSONA FÍSICA QUE SE INDICA EN EL APARTADO 2.- DE LA CARÁTULA; Y POR LA OTRA PARTE, <?= $siMenor ? 'LA PERSONA MENOR DE EDAD SEÑALADA EN EL APARTADO 5.- DE LA CARÁTULA, REPRESENTADA EN ESTE ACTO POR SU MAMÁ, PAPÁ O TUTOR' : ($siDependiente ? 'LA PERSONA FÍSICA SEÑALADA EN EL APARTADO 5.- DE LA CARÁTULA, REPRESENTADA EN ESTE ACTO POR SU RESPONSABLE AUTORIZADO' : 'LA PERSONA FÍSICA SEÑALADA EN EL APARTADO 5.- DE LA CARÁTULA, POR SU PROPIO DERECHO') ?>, A QUIEN EN LO SUCESIVO SE LE DENOMINARÁ COMO “EL AFILIADO”; Y CUANDO LOS ANTES NOMBRADOS ACTÚEN DE MANERA CONJUNTA, SE LES DENOMINARÁ COMO “LAS PARTES”; QUIENES SE SUJETAN AL TENOR DE LAS DECLARACIONES Y CLÁUSULAS SIGUIENTES:</p>

  <h2>D E C L A R A C I O N E S</h2>
  <h4>I.- Declara “EL PRESTADOR” por conducto de su representación:</h4>
  <p>A. Que, su representada es una sociedad mercantil constituida conforme a las leyes de los Estados Unidos Mexicanos, según consta en la escritura pública número <?= $e($data['prestador_escritura_numero']) ?>, del volumen <?= $e($data['prestador_escritura_volumen']) ?> de fecha <?= $e($data['prestador_escritura_fecha']) ?>, otorgada ante la fe del Licenciado <?= $e($data['prestador_notario_nombre']) ?>, Notario Público Titular de la Notaría Pública número <?= $e($data['prestador_notaria_numero']) ?> de las del Distrito Judicial de Puebla, Estado de Puebla, cuyo primer testimonio se encuentra inscrito ante las oficinas del Registro Público de Comercio del Distrito Judicial de Puebla, Estado de Puebla, bajo el Folio Mercantil Electrónico: <?= $e($data['prestador_folio_mercantil']) ?>, por virtud del cual se llevó a cabo la Constitución de la persona moral denominada <?= $e($data['prestador_razon_social']) ?>.</p>
  <p>B. Que, la persona física que la representa en este acto, señalada en el Apartado 2.- de la Carátula, cuenta con todas y cada una de las facultades necesarias para la celebración del presente contrato, las cuales se desprenden del instrumento descrito en el punto declarativo inmediato anterior, mismas que manifiesta bajo protesta de decir verdad que no le han sido suspendidas, revocadas o limitadas en forma alguna.</p>
  <p>C. Que, su representada tiene como domicilio fiscal el señalado en el Apartado 3.- de la Carátula del presente contrato, mismo que designa como domicilio convencional para cualquier cuestión relacionada con la celebración del presente contrato.</p>
  <p>D. Que, su representada se encuentra inscrita en el Registro Federal de Contribuyentes bajo la clave señalada en el Apartado 4.- de la Carátula.</p>
  <p>E. Que, ha desarrollado y es su deseo comparecer a la celebración del presente instrumento con la finalidad de enajenar en favor de “EL AFILIADO”, una Tarjeta de Descuento que da acceso a “UN PROGRAMA DE BENEFICIOS QUE OTORGA DESCUENTOS A LOS COSTOS Y PERMITE RECIBIR SERVICIOS MÉDICOS PRIVADOS DE ALTA CALIDAD DE FORMA ACCESIBLE, CLARA Y SIN RESTRICCIONES DENTRO DE LA RED DE HOSPITALES 50 (FIFTY) DOCTORS CON SEDE EN EL ESTADO DE PUEBLA”, en lo sucesivo “LA TARJETA DE DESCUENTO”, en los términos y condiciones que se establecerán más adelante.</p>
  <p>F. Que, su representada no es una Aseguradora reconocida por la Comisión Nacional de Seguros y Fianzas sino una empresa dedicada, entre otros, a la operación y administración de establecimientos destinados a la atención y asistencia de enfermos, por lo que la enajenación de “LA TARJETA DE DESCUENTO” únicamente constituye un acto de comercio que brindará a “EL AFILIADO” acceso a un programa de beneficios como ha quedado descrito anteriormente.</p>

  <h4>II.- Declara “EL AFILIADO”<?= $requiereResponsable ? ' por conducto de la persona responsable firmante' : ', por su propio derecho' ?>:</h4>
  <?php if ($requiereResponsable): ?>
    <p>A. Que, el nombre de “EL AFILIADO”/paciente se señala en el Apartado 5.- de la Carátula: <?= $e($nombreAfiliado) ?>, con fecha de nacimiento <?= $e($data['fecha_nacimiento'] ?? '') ?> y nacionalidad <?= $e($data['afiliado_nacionalidad'] ?: 'Pendiente') ?>. Comparece representado por <?= $e($data['tutor_nombre_completo'] ?: 'Pendiente') ?>, en carácter de <?= $e($data['relacion_responsable_paciente'] ?: ($siMenor ? 'MAMÁ/PAPÁ/TUTOR' : 'RESPONSABLE AUTORIZADO')) ?>, quien declara estar facultado para celebrar el presente contrato, firmarlo digitalmente, administrar usuario y contraseña, aceptar avisos, efectuar pagos y gestionar los beneficios de “LA TARJETA DE DESCUENTO” en favor del paciente.</p>
    <p>B. Que, la persona responsable se identifica con <?= $tutorMx ? 'identificación oficial mexicana vigente' : 'identificación oficial o pasaporte vigente expedido por autoridad competente' ?>, tipo <?= $e($data['tutor_tipo_identificacion']) ?>, número <?= $e($data['tutor_numero_identificacion'] ?: 'Pendiente') ?>. <?= $tutorMx ? 'En caso de ser mexicano, deberá integrar CURP y documentación fiscal cuando aplique.' : 'Por tratarse de persona extranjera/no mexicana, no se exige INE, CURP ni constancia fiscal mexicana salvo que declare RFC mexicano.' ?> <?= $siDependiente ? 'Motivo de apoyo declarado: '.$e($data['motivo_responsable'] ?: 'Pendiente').'.' : '' ?></p>
  <?php else: ?>
    <p>A. Que, su nombre se señala en el Apartado 5.- de la Carátula, es una persona física de nacionalidad <?= $e($data['afiliado_nacionalidad'] ?: 'Pendiente') ?>, en pleno ejercicio de sus derechos, legal y jurídicamente capaz para celebrar el presente Contrato, quien se identifica con <?= $e($identificacionAfiliado) ?>, tipo <?= $e($data['afiliado_tipo_identificacion']) ?>, número <?= $e($data['afiliado_numero_identificacion'] ?: 'Pendiente') ?>, que en copia simple o archivo digital se agrega al cuerpo del presente contrato como ANEXO 1.</p>
  <?php endif; ?>
  <p>B. Que, tiene como domicilio particular el señalado en el Apartado 6.- de la Carátula, mismo que designa como domicilio convencional para cualquier cuestión relacionada con la celebración del presente contrato, tal y como lo acredita con el comprobante de domicilio que en copia simple o archivo digital se agrega al cuerpo del presente contrato como ANEXO 2.</p>
  <p>C. Que, su CURP es <?= $e($data['afiliado_curp']) ?> y su RFC/identificación fiscal es <?= $e($data['afiliado_rfc']) ?>; asimismo manifiesta que cuenta con capacidad económica para obligarse en términos del presente contrato y que los recursos con los que cubrirá sus obligaciones provendrán de fuentes lícitas. En caso de nacionalidad extranjera/no mexicana, se tendrán por no aplicables CURP, INE y constancia fiscal mexicana salvo manifestación expresa de residencia fiscal o RFC mexicano.</p>
  <p>D. Que, es su deseo comparecer a la celebración del presente instrumento con la finalidad de adquirir “LA TARJETA DE DESCUENTO” de acuerdo con los términos y condiciones que se establecen a continuación.</p>
  <p>E. Que, previo a la celebración del presente contrato fue informado y manifiesta expresamente que reconoce que “EL PRESTADOR” no es una Aseguradora reconocida por la Comisión Nacional de Seguros y Fianzas y que las actividades comerciales objeto del presente contrato no consisten en la contratación de un seguro, de la índole que fuere, sino que únicamente implica la adquisición de una tarjeta de descuento que da acceso a un programa de beneficios que otorga descuentos a los costos y permite recibir servicios médicos privados de alta calidad de forma accesible, clara y sin restricciones dentro de la red de hospitales 50 (FIFTY) Doctors con sede en el Estado de Puebla.</p>
  <p>F. Que, reconoce que “EL PRESTADOR” se dedica a la operación de centros hospitalarios y que la emisión de “LA TARJETA DE DESCUENTO” únicamente corresponde a la intención de este último de crear un programa de descuentos para el acceso a los servicios prestados por la Red de Hospitales 50 (FIFTY) Doctors en el Estado de Puebla.</p>

  <h4>III.- Declaran conjuntamente “LAS PARTES”:</h4>
  <p>1. Que, se reconocen recíprocamente la personalidad con la que comparecen a la celebración del presente acuerdo de voluntades.</p>
  <p>2. Que, el presente contrato es el instrumento que las vincula en sus derechos y obligaciones.</p>
  <p>3. Que, es su deseo celebrar el presente contrato y han negociado libremente los términos y condiciones del mismo con pleno conocimiento de sus alcances e implicaciones jurídicas, por lo que en su celebración no existe dolo, error, mala fe, lesión o cualquier otro vicio del consentimiento que pudiese afectarlo de inexistencia o nulidad.</p>

  <h2>C L Á U S U L A S</h2>
  <h4>PRIMERA.- OBJETO.</h4>
  <p>El objeto del presente Contrato es que “EL AFILIADO” adquiera de “EL PRESTADOR”, a título oneroso y temporal, el derecho de uso ilimitado y sin restricción alguna de “LA TARJETA DE DESCUENTO” emitida por <?= $e($data['prestador_razon_social']) ?>, la cual consiste en que “EL AFILIADO” aproveche y acceda a “UN PROGRAMA DE BENEFICIOS QUE OTORGA DESCUENTOS A LOS COSTOS Y PERMITE RECIBIR SERVICIOS MÉDICOS PRIVADOS DE ALTA CALIDAD DE FORMA ACCESIBLE, CLARA Y SIN RESTRICCIONES DENTRO DE LA RED DE HOSPITALES 50 (FIFTY) DOCTORS CON SEDE EN EL ESTADO DE PUEBLA”.</p>
  <p>Estableciendo que, la comercialización de “LA TARJETA DE DESCUENTO” por parte de “EL PRESTADOR” en ningún momento constituirá la venta, promoción o por cualquier medio la contratación de una póliza de seguro, bajo el entendido de que “EL PRESTADOR” no es una aseguradora reconocida por la Comisión Nacional de Seguros y Fianzas (CNSF); sino que comercializa “LA TARJETA DE DESCUENTO” en favor de terceros con la finalidad de otorgar descuentos a los precios respecto de los servicios médicos que presta en el territorio nacional.</p>

  <h4>SEGUNDA.- PRECIO DE “LA TARJETA DE DESCUENTO”.</h4>
  <p>“LAS PARTES” establecen de común acuerdo que “LA TARJETA DE DESCUENTO” tendrá como costo <?= $e($data['frecuencia_texto']) ?> la cantidad señalada en el Apartado 8.- de la Carátula del presente contrato; cantidad que ya incluye IVA, y la cual deberá ser cubierta por “EL AFILIADO” en favor de “EL PRESTADOR” dentro de los primeros 5 (cinco) días de cada mes, sin necesidad de gestiones o avisos de cobro, ya sea mediante:</p>
  <p>(i) Transferencia electrónica de fondos a la cuenta bancaria señalada en el Apartado 9.- de la Carátula del presente contrato y de la cual es titular “EL PRESTADOR”.</p>
  <p>(ii) Cheque que se recibirá salvo buen cobro en el Domicilio de “EL PRESTADOR” señalado en el Apartado 3.- de la Carátula del presente contrato, y que en caso de no ser pagado por falta de fondos suficientes o por otras causas imputables a “EL AFILIADO”, éste último está de acuerdo en que deberá cubrir a “EL PRESTADOR” el 20% (veinte por ciento) del monto del cheque por concepto de indemnización por daños y perjuicios en términos del artículo 193 de la Ley General de Títulos y Operaciones de Crédito, independientemente de cualquier otro cargo que se pudiera generar.</p>
  <p>(iii) Cargos mensuales automáticos recurrentes a la tarjeta de crédito de “EL AFILIADO” según los datos señalados en el Apartado 11.- de la Carátula del presente contrato, quien manifiesta bajo protesta de decir verdad que autoriza a “EL PRESTADOR” a realizar los cargos mensuales correspondientes por el costo <?= $e($data['frecuencia_texto']) ?> de “LA TARJETA DE DESCUENTO” en dicha tarjeta o en la tarjeta que por renovación, reposición, robo o extravío le haya asignado el banco emisor. La autorización estará vigente mientras “EL AFILIADO” no haya notificado a “EL PRESTADOR” por escrito y con acuse de recibo su deseo de cancelar su afiliación o no renovarla, o en su defecto, realizar su baja respectiva en el sitio web o aplicación de “EL PRESTADOR”.</p>
  <p>Esta autorización no exime a “EL AFILIADO” del pago <?= $e($data['frecuencia_texto']) ?> por el uso de “LA TARJETA DE DESCUENTO” y demás obligaciones contractuales, por lo que, en caso de que el cobro no sea autorizado por el banco emisor o por cualquier razón no pueda realizarse, “EL AFILIADO” deberá notificar tal situación a “EL PRESTADOR” a la dirección de correo electrónico <?= $e($data['prestador_correo_contacto']) ?>, a efecto de solicitar una forma de pago diversa, quedando obligado a cubrir de inmediato el pago correspondiente.</p>
  <p>(iv) Cualquier otro medio de pago aceptado por “EL PRESTADOR”, mismo que se dará a conocer a través de sus medios oficiales de comunicación.</p>
  <p>“EL PRESTADOR” podrá variar unilateralmente el costo mensual de “LA TARJETA DE DESCUENTO”, previo aviso a “EL AFILIADO” con 30 (treinta) días de anticipación a través de sus medios oficiales de comunicación.</p>
  <p>Para el caso de que “EL AFILIADO” adquiera y cubra el precio de “LA TARJETA DE DESCUENTO” y posteriormente deje de pagar una mensualidad, deberá cubrir a “EL PRESTADOR”, por concepto de cuota de reactivación, la cantidad señalada en el Apartado 10.- de la Carátula por cada mes que haya interrumpido y/o no haya cubierto el precio de “LA TARJETA DE DESCUENTO”, hasta la fecha en que pretenda volver a adquirirla.</p>

  <h4>TERCERA.- VIGENCIA DE “LA TARJETA DE DESCUENTO”.</h4>
  <p>“LA TARJETA DE DESCUENTO” objeto del presente contrato tendrá una vigencia de <?= $e($data['vigencia_texto']) ?> contados a partir de que “EL AFILIADO” cubra a “EL PRESTADOR” el precio establecido anteriormente, en el entendido de que la vigencia del presente contrato y de “LA TARJETA DE DESCUENTO” se prorrogarán automáticamente sin necesidad de celebrar documento adicional entre “LAS PARTES” siempre y cuando “EL AFILIADO” cubra, de mes en mes o en la frecuencia contratada, el precio vigente de “LA TARJETA DE DESCUENTO”.</p>
  <p>“EL AFILIADO” tendrá derecho a revocar su consentimiento dentro de los 5 (cinco) días siguientes a la entrega de “LA TARJETA DE DESCUENTO” o la firma del presente contrato, lo que ocurra último, sin responsabilidad alguna, siempre y cuando no haya obtenido beneficio alguno por el uso de “LA TARJETA DE DESCUENTO”.</p>

  <h4>CUARTA.- BENEFICIOS DE “LA TARJETA DE DESCUENTO”.</h4>
  <p>“EL AFILIADO”, de forma exclusiva, personal e intransferible, gozará de forma gratuita de los servicios que se mencionan a continuación:</p>
  <ul><li>Consultas gratuitas ilimitadas de medicina general (no de especialidad) en la red de Hospitales 50 (FIFTY) Doctors en el Estado de Puebla, únicamente con los doctores afiliados al programa de Pasaporte a tu Salud.</li><li>Consultas de urgencia gratuitas en la red de Hospitales 50 (FIFTY) Doctors en el Estado de Puebla.</li></ul>
  <p>No así respecto de los servicios que, de manera enunciativa más no limitativa, se describen a continuación:</p>
  <ul><li>Hospitalización dentro de la red de Hospitales 50 (FIFTY) Doctors en el Estado de Puebla, sujeto a la disponibilidad de cada uno de ellos.</li><li>Consultas de especialidad ilimitadas a costo preferencial, con médicos especialistas pertenecientes al programa PATS.</li><li>Acceso a farmacia PATS con costos reducidos de medicamentos genéricos.</li><li>Imagenología y laboratorios ilimitados con costos preferenciales.</li><li>Acceso a cirugías con cuota de recuperación preferente, con o sin honorarios médicos incluidos según corresponda.</li></ul>
  <p>Dichos servicios generarán, por evento, el pago de una cuota con cargo a “EL AFILIADO”, misma que resultará de aplicar los porcentajes de descuento que se desprenden del ANEXO 4 del presente contrato a los precios publicados al público en general o los precios preferenciales indicados.</p>
  <p>Mientras “LA TARJETA DE DESCUENTO” se encuentre vigente, “EL AFILIADO” gozará de todos los beneficios que la misma le otorga; sin embargo, para el caso de que requiera cirugía o procedimiento quirúrgico en quirófano, deberá haber sufragado por adelantado la adquisición de “LA TARJETA DE DESCUENTO” por un periodo de 12 (doce) meses y encontrarse dentro de dicho periodo de vigencia.</p>

  <h4>QUINTA.- OBLIGACIONES DE “EL PRESTADOR”.</h4>
  <p>“EL PRESTADOR” se obliga a: (i) otorgar a “EL AFILIADO” el acceso ilimitado a “LA TARJETA DE DESCUENTO” durante la vigencia del contrato; (ii) mantener actualizada y operativa la Red de Hospitales 50 (FIFTY) Doctors en el Estado de Puebla; (iii) proporcionar a “EL AFILIADO”, de forma digital, “LA TARJETA DE DESCUENTO” dentro de los 5 (cinco) días hábiles siguientes al primer pago; e (iv) informar por escrito cualquier modificación a la red de hospitales o al tabulador de cuotas con al menos 10 (diez) días de anticipación.</p>

  <h4>SEXTA.- OBLIGACIONES DE “EL AFILIADO”.</h4>
  <p>“EL AFILIADO” se obliga a: (i) pagar puntualmente el precio de “LA TARJETA DE DESCUENTO”; (ii) utilizarla de forma exclusiva, personal e intransferible; (iii) cubrir directamente a los hospitales y con anterioridad a recibir el servicio médico las cuotas de recuperación según tabulador vigente; (iv) presentar identificación oficial y “LA TARJETA DE DESCUENTO” o código QR cada vez que haga uso de beneficios; y (v) notificar por escrito cualquier cambio de domicilio o datos de contacto en un plazo no mayor a 5 (cinco) días.</p>

  <h4>SÉPTIMA.- ACCESO A LOS BENEFICIOS Y PROCEDIMIENTO.</h4>
  <p>Para hacer uso de “LA TARJETA DE DESCUENTO”, “EL AFILIADO” deberá agendar sus citas directamente con los doctores pertenecientes a la Red de Hospitales 50 (FIFTY) Doctors, que en ese momento se encuentren adscritos al programa de beneficios, a través de la aplicación oficial, página de internet oficial de PATS o medios oficiales que indique “EL PRESTADOR”.</p>
  <p>“EL AFILIADO” se obliga a pagar directamente al médico especialista perteneciente al programa el costo de la consulta de especialidad de que se trate, en términos de los porcentajes de descuento del ANEXO 4. En caso de no estar facultado para asistir por fuerza mayor, tendrá un plazo de 30 (treinta) días contados a partir de haber generado la cita para solicitar una nueva consulta médica.</p>

  <h4>OCTAVA.- EXCLUSIONES Y LIMITACIONES.</h4>
  <p>Los beneficios no incluirán: (i) trasplantes de órganos; (ii) tratamientos experimentales; (iii) tratamientos de oncología a excepción de algunas cirugías; (iv) medicamentos extra hospitalarios que no estén recogidos en el catálogo de Farmacia PATS; (v) atención médica con especialistas no adscritos o no publicados en los medios oficiales; y (vi) cualquier servicio no listado expresamente.</p>

  <h4>NOVENA.- CAUSAS DE TERMINACIÓN.</h4>
  <p>El contrato podrá terminarse por falta de pago, mutuo consentimiento por escrito o incumplimiento de cualquiera de las cláusulas por cualquiera de “LAS PARTES”. En caso de terminación, “EL AFILIADO” no tendrá derecho a exigir la devolución de cantidad alguna.</p>

  <h4>DÉCIMA.- CANCELACIÓN VOLUNTARIA.</h4>
  <p>“EL AFILIADO” podrá cancelar “LA TARJETA DE DESCUENTO” mediante aviso por escrito con 30 (treinta) días de anticipación. Dicha cancelación surtirá efectos a partir del siguiente periodo mensual y no generará reembolso de pagos ya realizados.</p>

  <h4>DÉCIMA PRIMERA.- PROTECCIÓN DE DATOS PERSONALES.</h4>
  <p>“LAS PARTES” acuerdan que el tratamiento de datos personales se sujetará a la Ley Federal de Protección de Datos Personales en Posesión de los Particulares. “EL AFILIADO” autoriza expresamente el uso de sus datos para la gestión de “LA TARJETA DE DESCUENTO”. El aviso de privacidad se integra al presente contrato como ANEXO 5.</p>

  <h4>DÉCIMA SEGUNDA.- RESPONSABILIDAD.</h4>
  <p>“EL AFILIADO” reconoce y acepta que “LA TARJETA DE DESCUENTO” es emitida y administrada directamente por <?= $e($data['prestador_razon_social']) ?>, quien es responsable de la operación de la red de descuentos, afiliación de prestadores médicos y prestación de cualquier servicio relacionado con “LA TARJETA DE DESCUENTO”.</p>
  <p>En consecuencia, “EL PRESTADOR” no tendrá responsabilidad directa ni indirecta por la prestación, calidad, eficacia, resultado, daño, perjuicio, lesión, complicación, secuela, evento adverso o consecuencia derivada de servicios médicos recibidos, incluyendo aquellos ocasionados por negligencia, impericia o mala praxis de profesionales de la salud o prestadores afiliados. Cualquier relación derivada de la prestación de servicios médicos se establece directamente entre “EL AFILIADO” y los prestadores de servicios de salud correspondientes. Esta limitación subsistirá a la terminación del contrato.</p>

  <h4>DÉCIMA TERCERA.- PREVENCIÓN DE LAVADO DE DINERO Y ORIGEN DE LOS RECURSOS.</h4>
  <p>“LAS PARTES” declaran bajo protesta de decir verdad que los recursos económicos, bienes y derechos que utilicen para cumplir obligaciones derivadas de este contrato tienen y tendrán origen lícito. “EL AFILIADO” manifiesta que el pago inicial y pagos futuros provienen de fuentes lícitas y no de actividades tipificadas como delitos.</p>
  <p>“LAS PARTES” reconocen que la prestación de servicios de comercio puede ser considerada actividad vulnerable, por lo que se obligan a proporcionar información y documentación requerida para integrar expediente de identificación e informar si tienen conocimiento de la existencia de beneficiario controlador.</p>

  <h4>DÉCIMA CUARTA.- CONFORMACIÓN DEL EXPEDIENTE DE IDENTIFICACIÓN.</h4>
  <p>“EL PRESTADOR” queda obligado a conformar y mantener un expediente de identificación de “EL AFILIADO”. Para tales efectos, “EL AFILIADO” se obliga a entregar los documentos aplicables: identificación oficial vigente o pasaporte, acta de nacimiento cuando aplique, comprobante de domicilio, constancia de situación fiscal cuando aplique, <?= $mx ? 'CURP' : 'documento equivalente de identificación' ?>, y declaración de dueño beneficiario.</p>
  <p>Cuando exista persona responsable, la documentación de identificación y representación deberá integrarse al expediente; la CIF/constancia fiscal corresponde al tutor cuando aplique. “EL PRESTADOR” conservará dicho expediente por un periodo mínimo de 5 (cinco) años contados a partir de que termine la vigencia del contrato o termine por cualquiera de sus causales, garantizando la confidencialidad de los datos personales.</p>

  <h4>DÉCIMA QUINTA.- CAUSAL ESPECÍFICA DE RESCISIÓN.</h4>
  <p>Será motivo de rescisión inmediata sin necesidad de declaración judicial y sin responsabilidad para la parte afectada cuando cualquiera de “LAS PARTES” se niegue a proporcionar información requerida para cumplimiento de la Ley Federal para la Prevención e Identificación de Operaciones con Recursos de Procedencia Ilícita, proporcione información falsa o aparezca en listas de personas bloqueadas emitidas por autoridad competente.</p>

  <h4>DÉCIMA SEXTA.- LEGISLACIÓN APLICABLE Y JURISDICCIÓN.</h4>
  <p>“LAS PARTES” establecen que la Procuraduría Federal del Consumidor es competente en vía administrativa para resolver cualquier controversia sobre interpretación o cumplimiento. Sin perjuicio de lo anterior, se someten expresamente a la jurisdicción de los tribunales competentes del fuero común del Distrito Judicial de Puebla, Estado de Puebla, renunciando de manera expresa e irrevocable a cualquier otro fuero o jurisdicción que pudiera corresponderles.</p>

  <p>Enteradas “LAS PARTES” del contenido y alcance del presente contrato, y entendidas de los derechos y obligaciones que contraen, firman el presente instrumento, incluyendo sus anexos, manifestando que no medió error, dolo, mala fe, violencia o lesión, ni vicio del consentimiento alguno, en la Ciudad de <?= $e($data['ciudad_firma']) ?>, Estado de <?= $e($data['estado_firma']) ?>, reconociendo que la fecha de firma es <?= $e($data['fecha_firma_larga']) ?>.</p>

  <div class="sign-grid">
    <div class="sign-box"><div class="line"></div><strong>“EL PRESTADOR”</strong><br><?= $e($data['prestador_razon_social']) ?><br>Representada por <?= $e($data['prestador_representante']) ?></div>
    <div class="sign-box"><?php if (!empty($data['firma_afiliado_base64'])): ?><img class="signature-img" src="<?= $e($data['firma_afiliado_base64']) ?>" alt="Firma digital"><?php else: ?><div class="line"></div><?php endif; ?><strong>“<?= $e($firmanteLabel) ?>”</strong><br><?= $e($firmanteNombre) ?></div>
  </div>

  <div class="annex"><h2>ANEXO 1<br><?= $e($anexoId) ?></h2><p>Se integra al expediente la identificación oficial cargada por el usuario en el formulario. Para mexicanos, corresponde a identificación oficial/INE cuando aplique. Para extranjeros/no mexicanos, corresponde a identificación oficial o pasaporte vigente; al menos el frente es obligatorio y el reverso será opcional cuando el documento no lo tenga.</p><p><strong>Tipo:</strong> <?= $e($data['afiliado_tipo_identificacion']) ?>. <strong>Emitida por / país emisor:</strong> <?= $e($data['afiliado_pais_documento_identidad']) ?>. <strong>Número:</strong> <?= $e($data['afiliado_numero_identificacion'] ?: 'Pendiente') ?>.</p></div>
  <div class="annex"><h2>ANEXO 2<br>COMPROBANTE DE DOMICILIO DE “EL AFILIADO”</h2><p>Se integra al expediente el comprobante de domicilio cargado por el usuario. Domicilio declarado: <?= $e($domAfiliado) ?>.</p></div>
  <div class="annex"><h2>ANEXO 3<br>CONSTANCIA DE SITUACIÓN FISCAL DE “EL AFILIADO”</h2><p><?= $e($anexoFiscal) ?>. En caso de pacientes representados, la constancia fiscal o CIF corresponde a la persona responsable cuando sea aplicable, no al menor. Para afiliados extranjeros/no mexicanos, no será obligatoria salvo que declaren RFC mexicano o residencia fiscal aplicable.</p></div>

  <div class="annex"><h2>ANEXO 4<br>CUOTAS DE RECUPERACIÓN Y/O PRECIOS BASE A CUBRIR A “EL PRESTADOR”</h2>
    <p>En el presente anexo se establecen los porcentajes de descuento a obtener como titular de “LA TARJETA DE DESCUENTO”, por lo que la cantidad a cubrir por “EL AFILIADO” directamente al hospital de la cadena 50 (FIFTY) Doctors o al doctor que preste el servicio se obtendrá de aplicar el porcentaje de descuento correspondiente al precio publicado por los medios oficiales o al precio vigente en el establecimiento.</p>
    <table><tr><th>Servicios / procedimientos</th><th>Descuentos</th></tr><tr><td>Consulta de urgencias</td><td>100%</td></tr><tr><td>Consulta de medicina general</td><td>100%</td></tr><tr><td>Habitación hospitalaria</td><td>90%</td></tr><tr><td>Uso de áreas de urgencias médicas</td><td>80%</td></tr><tr><td>Utilización de cubículos de terapia intensiva (UCIA-UCIN-UCIP)</td><td>75%</td></tr><tr><td>CEYE</td><td>75%</td></tr><tr><td>Uso quirófano</td><td>75%</td></tr><tr><td>Servicio de cuneros</td><td>75%</td></tr><tr><td>Materiales & medicamentos del cuadro básico, genéricos intercambiables</td><td>70%</td></tr><tr><td>Hemodinamia</td><td>70%</td></tr><tr><td>Imagenología</td><td>70%</td></tr><tr><td>Endoprótesis</td><td>70%</td></tr><tr><td>Osteosíntesis</td><td>70%</td></tr><tr><td>Prótesis</td><td>70%</td></tr><tr><td>Órtesis</td><td>70%</td></tr><tr><td>Laboratorio clínico</td><td>60%</td></tr></table>
    <p class="small">Los descuentos aplican con los proveedores suscritos al convenio de Pasaporte a tu Salud.</p>
    <table><tr><th>Servicios / procedimientos</th><th>Precios base</th></tr><tr><td>Consulta de especialidades médicas</td><td>$390.00</td></tr><tr><td>Colposcopía</td><td>$400.00</td></tr><tr><td>Retiro de puntos de sutura</td><td>$80.00</td></tr><tr><td>Aplicación de medicamento intramuscular</td><td>$60.00</td></tr><tr><td>Retiro de DIU</td><td>$500.00</td></tr><tr><td>Colocación de DIU</td><td>$700.00</td></tr><tr><td>Extracción de cuerpo extraño (oído y nariz)</td><td>$300.00</td></tr><tr><td>Lavado ótico</td><td>$250.00</td></tr><tr><td>Curación de sitio quirúrgico</td><td>$250.00</td></tr><tr><td>Retiro de yeso</td><td>$250.00</td></tr><tr><td>Visita día de hospitalización</td><td>$650.00</td></tr><tr><td>Visita de urgencias</td><td>$750.00</td></tr><tr><td>Día de terapia intensiva</td><td>$850.00</td></tr></table>
    <p class="small">Todos los precios incluyen IVA. La factura de servicios hospitalarios será emitida con el desglose correspondiente y el ahorro otorgado por ser titular de “LA TARJETA DE DESCUENTO”.</p>
    <p>Exclusiones y limitaciones: se aplicarán descuentos y precios especiales para el acompañante de “EL AFILIADO” en la misma habitación únicamente para la primera noche de hospitalización. Los precios y porcentajes de descuento darán derecho a la utilización de materiales y medicamentos del cuadro básico, genéricos intercambiables; cualquier otro tipo de medicación será cubierto directamente por “EL AFILIADO”. Los costos de procedimientos quirúrgicos incluyen honorarios médicos cuando así se indique. “EL AFILIADO” podrá atenderse con el médico tratante que elija, debiendo cubrir honorarios directamente a dicho médico, conservando el derecho a beneficios dentro de la red aplicable.</p>
    <div class="sign-box"><?php if (!empty($data['firma_afiliado_base64'])): ?><img class="signature-img" src="<?= $e($data['firma_afiliado_base64']) ?>" alt="Firma digital"><?php else: ?><div class="line"></div><?php endif; ?><strong>Firma de aceptación de “EL AFILIADO”</strong><br><?= $e($firmanteNombre) ?></div>
  </div>

  <div class="annex"><h2>ANEXO 5<br>AVISO DE PRIVACIDAD</h2>
    <p>En cumplimiento de las disposiciones establecidas en la Ley Federal de Protección de Datos Personales en Posesión de Particulares, su Reglamento y los lineamientos aplicables, “<?= $e($data['prestador_razon_social']) ?>” (en lo sucesivo “EL PRESTADOR”), con domicilio en <?= $e($data['prestador_domicilio']) ?>, da a conocer el Aviso de Privacidad al tenor del cual manejará por medio de su representación y/o empleados los datos personales y/o documentación proporcionada por el afiliado o usuario de “LA TARJETA DE DESCUENTO”.</p>
    <p>Se tendrá por aceptado expresamente el presente Aviso de Privacidad una vez proporcionados los datos personales y firmada digitalmente la aceptación del contrato, motivo por el cual “EL PRESTADOR” estará facultado para manejar la información conforme a la legislación aplicable.</p>
    <h4>Modificación del aviso de privacidad</h4><p>Este aviso podrá ser modificado o adecuado a las necesidades de “EL PRESTADOR”. Las modificaciones o actualizaciones serán incorporadas al presente aviso y estarán disponibles en la página de internet, domicilio de “EL PRESTADOR” o serán enviadas al último correo electrónico proporcionado.</p>
    <h4>Finalidad de la información</h4><p>La información será utilizada para: elaborar y mantener actualizada la base de usuarios; identificar afiliados; proporcionar la tarjeta digital; otorgar acceso al programa de beneficios; informar modificaciones a la red o tabulador; realizar análisis estadísticos internos y brindar un óptimo servicio médico.</p>
    <h4>Tipo de datos necesarios</h4><p>Se solicitarán datos de identificación, contacto, legales, contractuales y fiscales cuando aplique, incluyendo nombre completo, lugar y fecha de nacimiento, firma, identificación oficial, nacionalidad, CURP y RFC cuando sean aplicables, domicilio, teléfono y correo electrónico.</p>
    <h4>Transferencias de la información</h4><p>El usuario autoriza proporcionar información sin consentimiento adicional en los casos previstos por ley, resolución de autoridad competente, tratados aplicables, salvaguarda de interés público, procuración o administración de justicia, reconocimiento o defensa de derechos en procesos judiciales, y a socios comerciales, técnicos o estratégicos que asuman obligaciones de confidencialidad y seguridad equivalentes.</p>
    <h4>Limitación del uso o divulgación de datos y derechos ARCO</h4><p>El usuario podrá limitar el uso o divulgación de sus datos personales y ejercer derechos de acceso, rectificación, cancelación u oposición mediante solicitud escrita dirigida a “EL PRESTADOR” en su domicilio o al correo <?= $e($data['prestador_correo_contacto']) ?>, acompañando documento que acredite su identidad.</p>
    <h4>Revocación de consentimiento</h4><p>El usuario podrá revocar su consentimiento siguiendo el mismo procedimiento, considerando que para ciertos fines la revocación puede implicar la cancelación de “LA TARJETA DE DESCUENTO” y la imposibilidad de acceder al programa.</p>
    <p><strong>Nombre:</strong> <?= $e($firmanteNombre) ?><br><strong>Fecha:</strong> <?= $e($data['fecha_firma_larga']) ?></p>
    <div class="sign-box"><?php if (!empty($data['firma_afiliado_base64'])): ?><img class="signature-img" src="<?= $e($data['firma_afiliado_base64']) ?>" alt="Firma digital"><?php else: ?><div class="line"></div><?php endif; ?><strong>Firma</strong></div>
  </div>

  <div class="annex"><h2>ANEXO 6<br>DECLARACIÓN DE DUEÑO BENEFICIARIO</h2>
    <p>DE CONFORMIDAD CON LO DISPUESTO EN LOS ARTÍCULOS 18 FRACCIÓN I Y III DE LA LEY FEDERAL PARA PREVENCIÓN E IDENTIFICACIÓN DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILÍCITA, EL ARTÍCULO 15 DE SU REGLAMENTO Y EL ARTÍCULO 13 DE LAS REGLAS DE CARÁCTER GENERAL, MANIFIESTO BAJO PROTESTA DE DECIR VERDAD:</p>
    <h4>Datos de identificación del cliente</h4>
    <table><tr><th>Campo</th><th>Respuesta</th></tr><tr><td>Apellido paterno, materno y nombre(s)</td><td><?= $e($nombreAfiliado) ?></td></tr><tr><td>Fecha de nacimiento</td><td><?= $e($data['fecha_nacimiento'] ?? '') ?></td></tr><tr><td>País de nacimiento</td><td><?= $e($data['afiliado_pais_nacimiento']) ?></td></tr><tr><td>Nacionalidad</td><td><?= $e($data['afiliado_nacionalidad']) ?></td></tr><tr><td>Actividad, ocupación o profesión</td><td><?= $e($data['afiliado_actividad_ocupacion'] ?: 'Pendiente') ?></td></tr><tr><td>Estado civil</td><td><?= $e($data['afiliado_estado_civil'] ?: 'Pendiente') ?></td></tr><tr><td>Domicilio particular</td><td><?= $e($domAfiliado) ?></td></tr><tr><td>Teléfonos</td><td><?= $e($data['afiliado_telefono']) ?></td></tr><tr><td>Correo electrónico</td><td><?= $e($data['afiliado_correo']) ?></td></tr><tr><td>CURP</td><td><?= $e($data['afiliado_curp']) ?></td></tr><tr><td>RFC</td><td><?= $e($data['afiliado_rfc']) ?></td></tr><tr><td>Tipo de identificación</td><td><?= $e($data['afiliado_tipo_identificacion']) ?></td></tr><tr><td>Emitida por / país emisor</td><td><?= $e($data['afiliado_pais_documento_identidad']) ?></td></tr><tr><td>Número de identificación</td><td><?= $e($data['afiliado_numero_identificacion']) ?></td></tr></table>
    <h4>Datos de identificación de la operación</h4>
    <table><tr><th>Campo</th><th>Respuesta</th></tr><tr><td>Tipo de operación</td><td>Adquisición de tarjeta de descuento PATS</td></tr><tr><td>Monto de operación</td><td><?= $e($data['monto_contrato']) ?></td></tr><tr><td>Fecha de operación</td><td><?= $e($data['fecha_firma_larga']) ?></td></tr><tr><td>Forma de pago</td><td>Pasarela / medio autorizado por “EL PRESTADOR”</td></tr><tr><td>Moneda</td><td><?= $e($data['moneda'] ?? 'MXN') ?></td></tr></table>
    <h4>Información de la existencia del dueño beneficiario o beneficiario controlador</h4>
    <p>Declaro que soy el beneficiario directo de la operación y no existe ningún otro dueño beneficiario o beneficiario controlador: <strong><?= $e($beneficiarioDirecto) ?></strong>.</p>
    <h4>Aviso de privacidad</h4><p>Los datos personales serán protegidos y tratados conforme al Aviso de Privacidad contenido en el cuerpo del presente contrato y la legislación aplicable.</p>
    <p>H. Puebla de Zaragoza al <?= $e($data['dia_firma']) ?> del mes de <?= $e($data['mes_firma']) ?> del año <?= $e($data['anio_firma']) ?>.</p>
    <div class="sign-box"><?php if (!empty($data['firma_afiliado_base64'])): ?><img class="signature-img" src="<?= $e($data['firma_afiliado_base64']) ?>" alt="Firma digital"><?php else: ?><div class="line"></div><?php endif; ?><strong>Nombre y firma</strong><br><?= $e($firmanteNombre) ?></div>
  </div>

  <?php if ($requiereResponsable): ?>
  <div class="annex"><h2>ANEXO 7<br>DOCUMENTACIÓN Y ACEPTACIÓN DE LA PERSONA RESPONSABLE</h2><p><strong>Paciente:</strong> <?= $e($nombreAfiliado) ?>. <strong>CURP/ID:</strong> <?= $e($data['afiliado_curp']) ?>. <strong>Fecha de nacimiento:</strong> <?= $e($data['fecha_nacimiento'] ?? '') ?>.</p><p><strong>Persona responsable firmante:</strong> <?= $e($data['tutor_nombre_completo']) ?>. <strong>CURP:</strong> <?= $e($data['tutor_curp'] ?: 'No aplica') ?>. <strong>RFC/CIF:</strong> <?= $e($data['tutor_rfc'] ?: 'No aplica') ?>. <strong>Identificación:</strong> <?= $e($data['tutor_tipo_identificacion']) ?> <?= $e($data['tutor_numero_identificacion']) ?>.</p><p>La persona responsable acepta administrar usuario, contraseña, consentimientos, pagos y obligaciones contractuales del paciente, y reconoce que los beneficios corresponden al menor como paciente/afiliado real.</p></div>
  <?php endif; ?>

  <?php if ($siAdultoMayor): ?>
  <div class="annex"><h2>ANEXO OPERATIVO<br>REQUISITO ADULTO MAYOR</h2><p>El alta de adulto mayor requiere validación previa de dos pasaportes vigentes existentes por id_pasaporte y fecha de nacimiento. Esta relación deberá guardarse en el backend final para auditoría y control operativo.</p><p><strong>Pasaporte vigente 1:</strong> <?= $e($data['adulto_mayor_id_pasaporte_1'] ?? '') ?>. <strong>Fecha nacimiento:</strong> <?= $e($data['adulto_mayor_fecha_nacimiento_1'] ?? '') ?>.</p><p><strong>Pasaporte vigente 2:</strong> <?= $e($data['adulto_mayor_id_pasaporte_2'] ?? '') ?>. <strong>Fecha nacimiento:</strong> <?= $e($data['adulto_mayor_fecha_nacimiento_2'] ?? '') ?>.</p></div>
  <?php endif; ?>
</div>
